TCAN4550: tcan4x5x/TCAN4x5x_SPI.c File Reference
TCAN4x5x_SPI.c File Reference
#include "TCAN4x5x_SPI.h"
Functions
void AHB_WRITE_32 (uint16_t address, uint32_t data)
uint32_t AHB_READ_32 (uint16_t address)
void AHB_WRITE_BURST_START (uint16_t address, uint8_t words)
void AHB_WRITE_BURST_WRITE (uint32_t data)
void AHB_WRITE_BURST_END (void)
void AHB_READ_BURST_START (uint16_t address, uint8_t words)
uint32_t AHB_READ_BURST_READ (void)
void AHB_READ_BURST_END (void)
Function Documentation
AHB_READ_32()
uint32_t AHB_READ_32 (uint16_t address)
Definition at line 66 of file TCAN4x5x_SPI.c.
References AHB_READ_BURST_END(), AHB_READ_BURST_READ(), and AHB_READ_BURST_START().
Referenced by TCAN4x5x_Device_Configure(), TCAN4x5x_Device_ConfigureInterruptEnable(), TCAN4x5x_Device_DisableTestMode(), TCAN4x5x_Device_EnableTestMode(), TCAN4x5x_Device_ReadConfig(), TCAN4x5x_Device_ReadDeviceVersion(), TCAN4x5x_Device_ReadInterruptEnable(), TCAN4x5x_Device_ReadInterrupts(), TCAN4x5x_Device_ReadMode(), TCAN4x5x_Device_ReadTestMode(), TCAN4x5x_Device_SetMode(), TCAN4x5x_MCAN_ConfigureCCCRRegister(), TCAN4x5x_MCAN_ConfigureDataTiming_Raw(), TCAN4x5x_MCAN_ConfigureDataTiming_Simple(), TCAN4x5x_MCAN_ConfigureGlobalFilter(), TCAN4x5x_MCAN_ConfigureNominalTiming_Raw(), TCAN4x5x_MCAN_ConfigureNominalTiming_Simple(), TCAN4x5x_MCAN_DisableProtectedRegisters(), TCAN4x5x_MCAN_EnableProtectedRegisters(), TCAN4x5x_MCAN_ReadCCCRRegister(), TCAN4x5x_MCAN_ReadDataTimingFD_Raw(), TCAN4x5x_MCAN_ReadDataTimingFD_Simple(), TCAN4x5x_MCAN_ReadInterruptEnable(), TCAN4x5x_MCAN_ReadInterrupts(), TCAN4x5x_MCAN_ReadNextFIFO(), TCAN4x5x_MCAN_ReadNominalTiming_Raw(), TCAN4x5x_MCAN_ReadNominalTiming_Simple(), TCAN4x5x_MCAN_ReadRXBuffer(), TCAN4x5x_MCAN_ReadSIDFilter(), TCAN4x5x_MCAN_ReadXIDFilter(), TCAN4x5x_MCAN_WriteSIDFilter(), TCAN4x5x_MCAN_WriteTXBuffer(), TCAN4x5x_MCAN_WriteXIDFilter(), TCAN4x5x_MRAM_Configure(), TCAN4x5x_WDT_Configure(), TCAN4x5x_WDT_Disable(), TCAN4x5x_WDT_Enable(), TCAN4x5x_WDT_Read(), and TCAN4x5x_WDT_Reset().
AHB_READ_BURST_END()
void AHB_READ_BURST_END (void)
Definition at line 223 of file TCAN4x5x_SPI.c.
References SPI_CS_GPIO_PIN, SPI_CS_GPIO_PORT, and WAIT_FOR_IDLE.
Referenced by AHB_READ_32(), TCAN4x5x_MCAN_ReadNextFIFO(), and TCAN4x5x_MCAN_ReadRXBuffer().
AHB_READ_BURST_READ()
uint32_t AHB_READ_BURST_READ (void)
Definition at line 183 of file TCAN4x5x_SPI.c.
References SPI_HW_ADDR, and WAIT_FOR_IDLE.
Referenced by AHB_READ_32(), TCAN4x5x_MCAN_ReadNextFIFO(), TCAN4x5x_MCAN_ReadRXBuffer(), and TCAN4x5x_MCAN_ReadXIDFilter().
AHB_READ_BURST_START()
void AHB_READ_BURST_START (uint16_t address, uint8_t words)
Definition at line 155 of file TCAN4x5x_SPI.c.
References AHB_READ_OPCODE, SPI_CS_GPIO_PIN, SPI_CS_GPIO_PORT, SPI_HW_ADDR, and WAIT_FOR_TRANSMIT.
Referenced by AHB_READ_32(), TCAN4x5x_MCAN_ReadNextFIFO(), TCAN4x5x_MCAN_ReadRXBuffer(), and TCAN4x5x_MCAN_ReadXIDFilter().
AHB_WRITE_32()
void AHB_WRITE_32 (uint16_t address, uint32_t data)
Definition at line 50 of file TCAN4x5x_SPI.c.
References AHB_WRITE_BURST_END(), AHB_WRITE_BURST_START(), and AHB_WRITE_BURST_WRITE().
Referenced by TCAN4x5x_Device_ClearInterrupts(), TCAN4x5x_Device_ClearInterruptsAll(), TCAN4x5x_Device_ClearSPIERR(), TCAN4x5x_Device_Configure(), TCAN4x5x_Device_ConfigureInterruptEnable(), TCAN4x5x_Device_DisableTestMode(), TCAN4x5x_Device_EnableTestMode(), TCAN4x5x_Device_SetMode(), TCAN4x5x_MCAN_ClearInterrupts(), TCAN4x5x_MCAN_ClearInterruptsAll(), TCAN4x5x_MCAN_ConfigureCCCRRegister(), TCAN4x5x_MCAN_ConfigureDataTiming_Raw(), TCAN4x5x_MCAN_ConfigureDataTiming_Simple(), TCAN4x5x_MCAN_ConfigureGlobalFilter(), TCAN4x5x_MCAN_ConfigureInterruptEnable(), TCAN4x5x_MCAN_ConfigureNominalTiming_Raw(), TCAN4x5x_MCAN_ConfigureNominalTiming_Simple(), TCAN4x5x_MCAN_DisableProtectedRegisters(), TCAN4x5x_MCAN_EnableProtectedRegisters(), TCAN4x5x_MCAN_ReadNextFIFO(), TCAN4x5x_MCAN_ReadRXBuffer(), TCAN4x5x_MCAN_TransmitBufferContents(), TCAN4x5x_MCAN_WriteSIDFilter(), TCAN4x5x_MCAN_WriteXIDFilter(), TCAN4x5x_MRAM_Clear(), TCAN4x5x_MRAM_Configure(), TCAN4x5x_WDT_Configure(), TCAN4x5x_WDT_Disable(), TCAN4x5x_WDT_Enable(), and TCAN4x5x_WDT_Reset().
AHB_WRITE_BURST_END()
void AHB_WRITE_BURST_END (void)
Definition at line 138 of file TCAN4x5x_SPI.c.
References SPI_CS_GPIO_PIN, SPI_CS_GPIO_PORT, and WAIT_FOR_IDLE.
Referenced by AHB_WRITE_32(), and TCAN4x5x_MCAN_WriteTXBuffer().
AHB_WRITE_BURST_START()
void AHB_WRITE_BURST_START (uint16_t address, uint8_t words)
Definition at line 88 of file TCAN4x5x_SPI.c.
References AHB_WRITE_OPCODE, SPI_CS_GPIO_PIN, SPI_CS_GPIO_PORT, SPI_HW_ADDR, and WAIT_FOR_TRANSMIT.
Referenced by AHB_WRITE_32(), and TCAN4x5x_MCAN_WriteTXBuffer().
AHB_WRITE_BURST_WRITE()
void AHB_WRITE_BURST_WRITE (uint32_t data)
Definition at line 118 of file TCAN4x5x_SPI.c.
References SPI_HW_ADDR, and WAIT_FOR_TRANSMIT.
Referenced by AHB_WRITE_32(), and TCAN4x5x_MCAN_WriteTXBuffer().