TCAN4550: main.c File Reference
main.c File Reference
#include <driverlib.h>
#include <msp430.h>
#include <TCAN4550.h>
Functions
void Init_GPIO (void)
void Init_Clock (void)
void Init_SPI (void)
void Init_CAN (void)
int main (void)
__interrupt void PORT1_ISR (void)
Variables
volatile uint8_t TCAN_Int_Cnt = 0
Function Documentation
Init_CAN()
void Init_CAN (void)
Definition at line 156 of file main.c.
References TCAN4x5x_MCAN_CCCR_Config::BRSE, TCAN4x5x_MCAN_CCCR_Config::DAR, TCAN4x5x_MCAN_Data_Timing_Simple::DataBitRatePrescaler, TCAN4x5x_MCAN_Data_Timing_Simple::DataTqAfterSamplePoint, TCAN4x5x_MCAN_Data_Timing_Simple::DataTqBeforeSamplePoint, TCAN4x5x_MCAN_XID_Filter::EFEC, TCAN4x5x_MCAN_XID_Filter::EFID1, TCAN4x5x_MCAN_XID_Filter::EFID2, TCAN4x5x_MCAN_XID_Filter::EFT, TCAN4x5x_MCAN_CCCR_Config::FDOE, MRAM_64_Byte_Data, TCAN4x5x_MCAN_Nominal_Timing_Simple::NominalBitRatePrescaler, TCAN4x5x_MCAN_Nominal_Timing_Simple::NominalTqAfterSamplePoint, TCAN4x5x_MCAN_Nominal_Timing_Simple::NominalTqBeforeSamplePoint, TCAN4x5x_Device_Interrupts::PWRON, TCAN4x5x_MCAN_Interrupt_Enable::RF0NE, TCAN4x5x_MRAM_Config::Rx0ElementSize, TCAN4x5x_MRAM_Config::Rx0NumElements, TCAN4x5x_MRAM_Config::Rx1ElementSize, TCAN4x5x_MRAM_Config::Rx1NumElements, TCAN4x5x_MRAM_Config::RxBufElementSize, TCAN4x5x_MRAM_Config::RxBufNumElements, TCAN4x5x_MCAN_SID_Filter::SFEC, TCAN4x5x_MCAN_SID_Filter::SFID1, TCAN4x5x_MCAN_SID_Filter::SFID2, TCAN4x5x_MCAN_SID_Filter::SFT, TCAN4x5x_MRAM_Config::SIDNumElements, TCAN4x5x_Device_ClearInterrupts(), TCAN4x5x_Device_ConfigureInterruptEnable(), TCAN4x5x_DEVICE_MODE_NORMAL, TCAN4x5x_Device_ReadInterrupts(), TCAN4x5x_Device_SetMode(), TCAN4x5x_MCAN_ClearInterruptsAll(), TCAN4x5x_MCAN_ConfigureCCCRRegister(), TCAN4x5x_MCAN_ConfigureDataTiming_Simple(), TCAN4x5x_MCAN_ConfigureInterruptEnable(), TCAN4x5x_MCAN_ConfigureNominalTiming_Simple(), TCAN4x5x_MCAN_DisableProtectedRegisters(), TCAN4x5x_MCAN_EnableProtectedRegisters(), TCAN4x5x_MCAN_WriteSIDFilter(), TCAN4x5x_MCAN_WriteXIDFilter(), TCAN4x5x_MRAM_Clear(), TCAN4x5x_MRAM_Configure(), TCAN4x5x_SID_SFEC_PRIORITYSTORERX0, TCAN4x5x_SID_SFT_CLASSIC, TCAN4x5x_XID_EFEC_PRIORITYSTORERX0, TCAN4x5x_XID_EFT_CLASSIC, TCAN4x5x_MRAM_Config::TxBufferElementSize, TCAN4x5x_MRAM_Config::TxBufferNumElements, TCAN4x5x_MRAM_Config::TxEventFIFONumElements, and TCAN4x5x_MRAM_Config::XIDNumElements.
Referenced by main().
Init_Clock()
void Init_Clock (void)
Definition at line 328 of file main.c.
Referenced by main().
Init_GPIO()
void Init_GPIO (void)
Definition at line 254 of file main.c.
Referenced by main().
Init_SPI()
void Init_SPI (void)
Definition at line 345 of file main.c.
Referenced by main().
main()
int main (void)
Definition at line 66 of file main.c.
References TCAN4x5x_MCAN_TX_Header::BRS, TCAN4x5x_MCAN_TX_Header::DLC, TCAN4x5x_MCAN_TX_Header::EFC, TCAN4x5x_MCAN_TX_Header::ESI, TCAN4x5x_MCAN_TX_Header::FDF, TCAN4x5x_MCAN_RX_Header::ID, TCAN4x5x_MCAN_TX_Header::ID, Init_CAN(), Init_Clock(), Init_GPIO(), Init_SPI(), MCAN_DLC_4B, TCAN4x5x_MCAN_TX_Header::MM, TCAN4x5x_MCAN_Interrupts::RF0N, TCAN4x5x_MCAN_TX_Header::RTR, RXFIFO0, TCAN4x5x_MCAN_ClearInterrupts(), TCAN4x5x_MCAN_ReadInterrupts(), TCAN4x5x_MCAN_ReadNextFIFO(), TCAN4x5x_MCAN_TransmitBufferContents(), TCAN4x5x_MCAN_WriteTXBuffer(), TCAN_Int_Cnt, and TCAN4x5x_MCAN_TX_Header::XTD.
PORT1_ISR()
__interrupt void PORT1_ISR (void)
Definition at line 370 of file main.c.
References TCAN_Int_Cnt.
Variable Documentation
TCAN_Int_Cnt
volatile uint8_t TCAN_Int_Cnt = 0
Definition at line 63 of file main.c.
Referenced by main(), and PORT1_ISR().